"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-08-03 20:27:10.521883+00:00

Generated from ``chaudron.domain.models`` and then adjusted in two places the
autogenerator cannot see.

*The ``pg_trgm`` extension.* The model installs it through a ``before_create``
listener on the metadata, which only ``create_all`` fires -- a migration does
not. Without the statement below, ``ix_product_name_trgm`` fails with
"operator class gin_trgm_ops does not exist".

*The enum types.* ``op.drop_table`` leaves a native PostgreSQL enum behind, so a
``downgrade`` followed by an ``upgrade`` would fail on "type already exists".
They are dropped explicitly at the end of ``downgrade``.
"""


from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


#: Native enum types created as a side effect of the columns that use them.
_ENUM_TYPES: tuple[str, ...] = (
    "membership_role",
    "quantity_dimension",
    "storage_kind",
    "product_source",
    "expiry_date_kind",
    "stock_entry_source",
    "stock_movement_kind",
    "shopping_item_origin",
    "receipt_status",
    "receipt_line_match_status",
    "recipe_status",
    "ingredient_availability",
    "llm_provider_mode",
    "llm_purpose",
    "llm_config_status",
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Required by ix_product_name_trgm, created below. Needs the connecting role
    # to hold CREATE on the database -- true for a database the deploy owns.
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.create_table(
        "household",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column(
            "timezone", sa.String(length=64), server_default=sa.text("'UTC'"), nullable=False
        ),
        sa.Column(
            "default_currency", sa.String(length=3), server_default=sa.text("'CHF'"), nullable=False
        ),
        sa.Column(
            "is_instance_owner", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "default_currency ~ '^[A-Z]{3}$'", name=op.f("ck_household_currency_format")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_household")),
    )
    op.create_index(
        "uq_household_instance_owner",
        "household",
        [sa.literal_column("(true)")],
        unique=True,
        postgresql_where=sa.text("is_instance_owner"),
    )
    op.create_table(
        "llm_provider",
        sa.Column("code", sa.String(length=40), nullable=False),
        sa.Column("display_name", sa.String(length=80), nullable=False),
        sa.Column("requires_api_key", sa.Boolean(), nullable=False),
        sa.Column("requires_base_url", sa.Boolean(), nullable=False),
        sa.Column("default_model", sa.String(length=120), nullable=True),
        sa.Column(
            "default_supports_vision", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "default_supports_structured_output",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column("default_max_context_tokens", sa.Integer(), nullable=True),
        sa.Column("is_enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("sort_order", sa.SmallInteger(), server_default=sa.text("0"), nullable=False),
        sa.PrimaryKeyConstraint("code", name=op.f("pk_llm_provider")),
    )
    op.create_table(
        "unit",
        sa.Column("code", sa.String(length=16), nullable=False),
        sa.Column(
            "dimension",
            sa.Enum("mass", "volume", "count", name="quantity_dimension"),
            nullable=False,
        ),
        sa.Column("factor_to_canonical", sa.Numeric(precision=18, scale=9), nullable=False),
        sa.Column("symbol", sa.String(length=16), nullable=False),
        sa.Column("is_canonical", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("sort_order", sa.SmallInteger(), server_default=sa.text("0"), nullable=False),
        sa.CheckConstraint("factor_to_canonical > 0", name=op.f("ck_unit_factor_positive")),
        sa.PrimaryKeyConstraint("code", name=op.f("pk_unit")),
        sa.UniqueConstraint("code", "dimension", name="uq_unit_code_dimension"),
    )
    op.create_index(
        "uq_unit_canonical_per_dimension",
        "unit",
        ["dimension"],
        unique=True,
        postgresql_where=sa.text("is_canonical"),
    )
    op.create_table(
        "user_account",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=True),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("disabled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_account")),
    )
    op.create_index(
        "uq_user_account_email_lower",
        "user_account",
        [sa.literal_column("lower(email)")],
        unique=True,
    )
    op.create_table(
        "household_member",
        sa.Column("household_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "role", sa.Enum("owner", "member", "viewer", name="membership_role"), nullable=False
        ),
        sa.Column(
            "joined_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("invited_by_user_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["household_id"],
            ["household.id"],
            name=op.f("fk_household_member_household_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["invited_by_user_id"],
            ["user_account.id"],
            name=op.f("fk_household_member_invited_by_user_id"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_account.id"],
            name=op.f("fk_household_member_user_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("household_id", "user_id", name=op.f("pk_household_member")),
    )
    op.create_index("ix_household_member_user_id", "household_member", ["user_id"], unique=False)
    op.create_table(
        "llm_provider_config",
        sa.Column("label", sa.String(length=80), nullable=False),
        sa.Column(
            "mode",
            sa.Enum("byok", "ollama", "instance_owner", name="llm_provider_mode"),
            nullable=False,
        ),
        sa.Column("provider_code", sa.String(length=40), nullable=False),
        sa.Column("model", sa.String(length=120), nullable=False),
        sa.Column("base_url", sa.Text(), nullable=True),
        sa.Column(
            "api_key_ciphertext",
            sa.LargeBinary(),
            nullable=True,
            comment="SECRET: AES-256-GCM ciphertext. Encryption key comes from the environment, never from this database. Never returned by the API; users only ever see api_key_last4.",
        ),
        sa.Column("api_key_last4", sa.String(length=4), nullable=True),
        sa.Column("api_key_encryption_key_id", sa.String(length=32), nullable=True),
        sa.Column("api_key_set_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("supports_vision", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "supports_structured_output",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column("max_context_tokens", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "unverified",
                "verified",
                "invalid_credentials",
                "disabled",
                name="llm_config_status",
            ),
            nullable=False,
        ),
        sa.Column("last_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("household_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(mode = 'byok' AND api_key_ciphertext IS NOT NULL) OR (mode = 'ollama' AND api_key_ciphertext IS NULL AND base_url IS NOT NULL) OR (mode = 'instance_owner' AND api_key_ciphertext IS NULL)",
            name=op.f("ck_llm_provider_config_mode_requirements"),
        ),
        sa.CheckConstraint(
            "(api_key_ciphertext IS NULL) = (api_key_last4 IS NULL) AND (api_key_ciphertext IS NULL) = (api_key_encryption_key_id IS NULL)",
            name=op.f("ck_llm_provider_config_secret_triplet"),
        ),
        sa.CheckConstraint(
            "char_length(api_key_last4) = 4", name=op.f("ck_llm_provider_config_last4_length")
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["user_account.id"],
            name=op.f("fk_llm_provider_config_created_by_user_id"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["household_id"],
            ["household.id"],
            name=op.f("fk_llm_provider_config_household_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["provider_code"],
            ["llm_provider.code"],
            name=op.f("fk_llm_provider_config_provider_code"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_llm_provider_config")),
        sa.UniqueConstraint("household_id", "id", name="uq_llm_provider_config_household_id"),
    )
    op.create_index(
        "ix_llm_provider_config_household_active",
        "llm_provider_config",
        ["household_id"],
        unique=False,
        postgresql_where=sa.text("archived_at IS NULL"),
    )
    op.create_index(
        "ix_llm_provider_config_invalid",
        "llm_provider_config",
        ["household_id"],
        unique=False,
        postgresql_where=sa.text("status = 'invalid_credentials'"),
    )
    op.create_index(
        "uq_llm_provider_config_label",
        "llm_provider_config",
        ["household_id", sa.literal_column("lower(label)")],
        unique=True,
        postgresql_where=sa.text("archived_at IS NULL"),
    )
    op.create_table(
        "product",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("household_id", sa.Uuid(), nullable=True),
        sa.Column("gtin", sa.String(length=14), nullable=True),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("brand", sa.Text(), nullable=True),
        sa.Column("category_tag", sa.Text(), nullable=True),
        sa.Column("image_url", sa.Text(), nullable=True),
        sa.Column("net_content_value", sa.Numeric(precision=12, scale=3), nullable=True),
        sa.Column("net_content_unit_code", sa.String(length=16), nullable=True),
        sa.Column("default_unit_code", sa.String(length=16), nullable=True),
        sa.Column("unit_weight_g", sa.Numeric(precision=12, scale=3), nullable=True),
        sa.Column("density_g_per_ml", sa.Numeric(precision=8, scale=4), nullable=True),
        sa.Column("default_shelf_life_days", sa.SmallInteger(), nullable=True),
        sa.Column(
            "source",
            sa.Enum("open_food_facts", "manual", "receipt_import", name="product_source"),
            nullable=False,
        ),
        sa.Column("off_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("off_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("gtin ~ '^[0-9]{8,14}$'", name=op.f("ck_product_gtin_digits")),
        sa.CheckConstraint(
            "(net_content_value IS NULL) = (net_content_unit_code IS NULL)",
            name=op.f("ck_product_net_content_pair"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["user_account.id"],
            name=op.f("fk_product_created_by_user_id"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["default_unit_code"],
            ["unit.code"],
            name=op.f("fk_product_default_unit_code"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["household_id"],
            ["household.id"],
            name=op.f("fk_product_household_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["net_content_unit_code"],
            ["unit.code"],
            name=op.f("fk_product_net_content_unit_code"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product")),
    )
    op.create_index(
        "ix_product_household_id",
        "product",
        ["household_id"],
        unique=False,
        postgresql_where=sa.text("household_id IS NOT NULL"),
    )
    op.create_index(
        "ix_product_name_trgm",
        "product",
        ["name"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
    )
    op.create_index(
        "uq_product_gtin_global",
        "product",
        ["gtin"],
        unique=True,
        postgresql_where=sa.text("household_id IS NULL AND gtin IS NOT NULL"),
    )
    op.create_index(
        "uq_product_household_gtin",
        "product",
        ["household_id", "gtin"],
        unique=True,
        postgresql_where=sa.text("household_id IS NOT NULL AND gtin IS NOT NULL"),
    )
    op.create_table(
        "shopping_list",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("is_default", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("household_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["household_id"],
            ["household.id"],
            name=op.f("fk_shopping_list_household_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_shopping_list")),
        sa.UniqueConstraint("household_id", "id", name="uq_shopping_list_household_id"),
    )
    op.create_index(
        "uq_shopping_list_default",
        "shopping_list",
        ["household_id"],
        unique=True,
        postgresql_where=sa.text("is_default AND archived_at IS NULL"),
    )
    op.create_table(
        "storage_location",
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("fridge", "freezer", "pantry", "cellar", "other", name="storage_kind"),
            nullable=False,
        ),
        sa.Column("sort_order", sa.SmallInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("household_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["household_id"],
            ["household.id"],
            name=op.f("fk_storage_location_household_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_storage_location")),
        sa.UniqueConstraint("household_id", "id", name="uq_storage_location_household_id"),
    )
    op.create_index(
        "uq_storage_location_name",
        "storage_location",
        ["household_id", sa.literal_column("lower(name)")],
        unique=True,
        postgresql_where=sa.text("archived_at IS NULL"),
    )
    op.create_table(
        "llm_purpose_binding",
        sa.Column("household_id", sa.Uuid(), nullable=False),
        sa.Column(
            "purpose",
            sa.Enum("recipe_generation", "receipt_parsing", name="llm_purpose"),
            nullable=False,
        ),
        sa.Column("llm_provider_config_id", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["household_id", "llm_provider_config_id"],
            ["llm_provider_config.household_id", "llm_provider_config.id"],
            name=op.f("fk_llm_purpose_binding_household_id_llm_provider_config_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["household_id"],
            ["household.id"],
            name=op.f("fk_llm_purpose_binding_household_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("household_id", "purpose", name=op.f("pk_llm_purpose_binding")),
    )
    op.create_table(
        "receipt",
        sa.Column("uploaded_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("image_object_key", sa.Text(), nullable=False),
        sa.Column("image_sha256", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum("uploaded", "parsing", "parsed", "confirmed", "failed", name="receipt_status"),
            nullable=False,
        ),
        sa.Column("merchant_name", sa.Text(), nullable=True),
        sa.Column("purchased_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("total_amount", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column(
            "provider_mode",
            sa.Enum("byok", "ollama", "instance_owner", name="llm_provider_mode"),
            nullable=True,
        ),
        sa.Column("provider_code", sa.String(length=40), nullable=True),
        sa.Column("model", sa.String(length=120), nullable=True),
        sa.Column("prompt_version", sa.String(length=40), nullable=True),
        sa.Column("llm_provider_config_id", sa.Uuid(), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("cost_micro", sa.BigInteger(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("raw_response", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("parse_error", sa.Text(), nullable=True),
        sa.Column("parsed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("household_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["household_id"],
            ["household.id"],
            name=op.f("fk_receipt_household_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["llm_provider_config_id"],
            ["llm_provider_config.id"],
            name=op.f("fk_receipt_llm_provider_config_id"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by_user_id"],
            ["user_account.id"],
            name=op.f("fk_receipt_uploaded_by_user_id"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_receipt")),
        sa.UniqueConstraint("household_id", "id", name="uq_receipt_household_id"),
        sa.UniqueConstraint("household_id", "image_sha256", name="uq_receipt_household_sha256"),
    )
    op.create_index(
        "ix_receipt_household_purchased",
        "receipt",
        ["household_id", sa.literal_column("purchased_at DESC NULLS LAST")],
        unique=False,
    )
    op.create_index(
        "ix_receipt_operator_cost",
        "receipt",
        ["created_at"],
        unique=False,
        postgresql_where=sa.text("provider_mode = 'instance_owner'"),
    )
    op.create_index(
        "ix_receipt_pending",
        "receipt",
        ["created_at"],
        unique=False,
        postgresql_where=sa.text("status IN ('uploaded', 'parsing')"),
    )
    op.create_table(
        "recipe_suggestion",
        sa.Column("requested_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("servings", sa.SmallInteger(), nullable=True),
        sa.Column("prep_minutes", sa.SmallInteger(), nullable=True),
        sa.Column("cook_minutes", sa.SmallInteger(), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("stock_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "provider_mode",
            sa.Enum("byok", "ollama", "instance_owner", name="llm_provider_mode"),
            nullable=False,
        ),
        sa.Column("provider_code", sa.String(length=40), nullable=False),
        sa.Column("model", sa.String(length=120), nullable=False),
        sa.Column("prompt_version", sa.String(length=40), nullable=False),
        sa.Column("llm_provider_config_id", sa.Uuid(), nullable=True),
        sa.Column("input_tokens", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("output_tokens", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("cached_input_tokens", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("cost_micro", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("finish_reason", sa.String(length=40), nullable=True),
        sa.Column(
            "status",
            sa.Enum("generated", "saved", "cooked", "discarded", name="recipe_status"),
            nullable=False,
        ),
        sa.Column("rating", sa.SmallInteger(), nullable=True),
        sa.Column("cooked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("household_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "input_tokens >= 0 AND output_tokens >= 0 AND cached_input_tokens >= 0 AND cost_micro >= 0",
            name=op.f("ck_recipe_suggestion_tokens_nonneg"),
        ),
        sa.CheckConstraint(
            "rating BETWEEN 1 AND 5", name=op.f("ck_recipe_suggestion_rating_range")
        ),
        sa.ForeignKeyConstraint(
            ["household_id"],
            ["household.id"],
            name=op.f("fk_recipe_suggestion_household_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["llm_provider_config_id"],
            ["llm_provider_config.id"],
            name=op.f("fk_recipe_suggestion_llm_provider_config_id"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["requested_by_user_id"],
            ["user_account.id"],
            name=op.f("fk_recipe_suggestion_requested_by_user_id"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recipe_suggestion")),
        sa.UniqueConstraint("household_id", "id", name="uq_recipe_suggestion_household_id"),
    )
    op.create_index(
        "ix_recipe_suggestion_household_created",
        "recipe_suggestion",
        ["household_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        "ix_recipe_suggestion_operator_cost",
        "recipe_suggestion",
        ["created_at", "model"],
        unique=False,
        postgresql_where=sa.text("provider_mode = 'instance_owner'"),
    )
    op.create_table(
        "receipt_line",
        sa.Column("receipt_id", sa.Uuid(), nullable=False),
        sa.Column("line_no", sa.SmallInteger(), nullable=False),
        sa.Column("raw_label", sa.Text(), nullable=False),
        sa.Column("quantity_value", sa.Numeric(precision=12, scale=3), nullable=True),
        sa.Column("quantity_unit_code", sa.String(length=16), nullable=True),
        sa.Column(
            "quantity_dimension",
            sa.Enum("mass", "volume", "count", name="quantity_dimension"),
            nullable=True,
        ),
        sa.Column("unit_price", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("total_price", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("matched_product_id", sa.Uuid(), nullable=True),
        sa.Column("match_confidence", sa.Numeric(precision=4, scale=3), nullable=True),
        sa.Column(
            "match_status",
            sa.Enum(
                "pending",
                "suggested",
                "confirmed",
                "rejected",
                "ignored",
                name="receipt_line_match_status",
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("household_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "match_confidence BETWEEN 0 AND 1", name=op.f("ck_receipt_line_confidence_range")
        ),
        sa.ForeignKeyConstraint(
            ["household_id", "receipt_id"],
            ["receipt.household_id", "receipt.id"],
            name=op.f("fk_receipt_line_household_id_receipt_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["household_id"],
            ["household.id"],
            name=op.f("fk_receipt_line_household_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["matched_product_id"],
            ["product.id"],
            name=op.f("fk_receipt_line_matched_product_id"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["quantity_unit_code", "quantity_dimension"],
            ["unit.code", "unit.dimension"],
            name=op.f("fk_receipt_line_quantity_unit_code_quantity_dimension"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_receipt_line")),
        sa.UniqueConstraint("receipt_id", "line_no", name="uq_receipt_line_no"),
    )
    op.create_index(
        "ix_receipt_line_pending",
        "receipt_line",
        ["household_id", "created_at"],
        unique=False,
        postgresql_where=sa.text("match_status IN ('pending', 'suggested')"),
    )
    op.create_table(
        "recipe_suggestion_ingredient",
        sa.Column("recipe_suggestion_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.SmallInteger(), nullable=False),
        sa.Column("raw_label", sa.Text(), nullable=False),
        sa.Column("quantity_value", sa.Numeric(precision=12, scale=3), nullable=True),
        sa.Column("quantity_unit_code", sa.String(length=16), nullable=True),
        sa.Column(
            "quantity_dimension",
            sa.Enum("mass", "volume", "count", name="quantity_dimension"),
            nullable=True,
        ),
        sa.Column("product_id", sa.Uuid(), nullable=True),
        sa.Column(
            "availability",
            sa.Enum("in_stock", "partial", "missing", "unknown", name="ingredient_availability"),
            nullable=False,
        ),
        sa.Column("is_optional", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("household_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["household_id", "recipe_suggestion_id"],
            ["recipe_suggestion.household_id", "recipe_suggestion.id"],
            name=op.f("fk_recipe_suggestion_ingredient_household_id_recipe_suggestion_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["household_id"],
            ["household.id"],
            name=op.f("fk_recipe_suggestion_ingredient_household_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
            name=op.f("fk_recipe_suggestion_ingredient_product_id"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["quantity_unit_code", "quantity_dimension"],
            ["unit.code", "unit.dimension"],
            name=op.f("fk_recipe_suggestion_ingredient_quantity_unit_code_quantity_dimension"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recipe_suggestion_ingredient")),
        sa.UniqueConstraint(
            "recipe_suggestion_id", "position", name="uq_recipe_suggestion_ingredient_position"
        ),
    )
    op.create_index(
        "ix_recipe_ingredient_missing",
        "recipe_suggestion_ingredient",
        ["household_id", "product_id"],
        unique=False,
        postgresql_where=sa.text("availability IN ('missing', 'partial')"),
    )
    op.create_table(
        "shopping_list_item",
        sa.Column("shopping_list_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=True),
        sa.Column("label", sa.Text(), nullable=True),
        sa.Column("quantity_value", sa.Numeric(precision=12, scale=3), nullable=True),
        sa.Column("quantity_unit_code", sa.String(length=16), nullable=True),
        sa.Column(
            "quantity_dimension",
            sa.Enum("mass", "volume", "count", name="quantity_dimension"),
            nullable=True,
        ),
        sa.Column(
            "origin",
            sa.Enum("manual", "low_stock", "recipe", name="shopping_item_origin"),
            nullable=False,
        ),
        sa.Column("origin_recipe_suggestion_id", sa.Uuid(), nullable=True),
        sa.Column("sort_order", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("checked_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("added_by_user_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("household_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "(quantity_value IS NULL) = (quantity_unit_code IS NULL) AND (quantity_value IS NULL) = (quantity_dimension IS NULL)",
            name=op.f("ck_shopping_list_item_quantity_triplet"),
        ),
        sa.CheckConstraint(
            "product_id IS NOT NULL OR label IS NOT NULL",
            name=op.f("ck_shopping_list_item_target_present"),
        ),
        sa.ForeignKeyConstraint(
            ["added_by_user_id"],
            ["user_account.id"],
            name=op.f("fk_shopping_list_item_added_by_user_id"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["checked_by_user_id"],
            ["user_account.id"],
            name=op.f("fk_shopping_list_item_checked_by_user_id"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["household_id", "shopping_list_id"],
            ["shopping_list.household_id", "shopping_list.id"],
            name=op.f("fk_shopping_list_item_household_id_shopping_list_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["household_id"],
            ["household.id"],
            name=op.f("fk_shopping_list_item_household_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["origin_recipe_suggestion_id"],
            ["recipe_suggestion.id"],
            name=op.f("fk_shopping_list_item_origin_recipe_suggestion_id"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
            name=op.f("fk_shopping_list_item_product_id"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["quantity_unit_code", "quantity_dimension"],
            ["unit.code", "unit.dimension"],
            name=op.f("fk_shopping_list_item_quantity_unit_code_quantity_dimension"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_shopping_list_item")),
    )
    op.create_index(
        "ix_shopping_list_item_pending",
        "shopping_list_item",
        ["household_id", "shopping_list_id", "sort_order"],
        unique=False,
        postgresql_where=sa.text("checked_at IS NULL"),
    )
    op.create_index(
        "ix_shopping_list_item_product",
        "shopping_list_item",
        ["product_id"],
        unique=False,
        postgresql_where=sa.text("product_id IS NOT NULL"),
    )
    op.create_table(
        "inventory_lot",
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("storage_location_id", sa.Uuid(), nullable=True),
        sa.Column("quantity_value", sa.Numeric(precision=12, scale=3), nullable=False),
        sa.Column("quantity_unit_code", sa.String(length=16), nullable=False),
        sa.Column(
            "quantity_dimension",
            sa.Enum("mass", "volume", "count", name="quantity_dimension"),
            nullable=False,
        ),
        sa.Column("quantity_canonical", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("initial_quantity_canonical", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("best_before", sa.Date(), nullable=True),
        sa.Column(
            "date_kind",
            sa.Enum("use_by", "best_before", "unknown", name="expiry_date_kind"),
            nullable=False,
        ),
        sa.Column("opened_at", sa.Date(), nullable=True),
        sa.Column("acquired_on", sa.Date(), nullable=True),
        sa.Column("unit_price", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column(
            "entry_source",
            sa.Enum(
                "manual",
                "barcode_scan",
                "receipt_import",
                "shopping_list",
                "recipe_leftover",
                name="stock_entry_source",
            ),
            nullable=False,
        ),
        sa.Column("source_receipt_line_id", sa.Uuid(), nullable=True),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("depleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("household_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "date_kind <> 'unknown' OR best_before IS NULL",
            name=op.f("ck_inventory_lot_date_kind_coherent"),
        ),
        sa.CheckConstraint(
            "(unit_price IS NULL) = (currency IS NULL)", name=op.f("ck_inventory_lot_price_pair")
        ),
        sa.CheckConstraint(
            "depleted_at IS NOT NULL OR quantity_canonical > 0",
            name=op.f("ck_inventory_lot_depleted_consistency"),
        ),
        sa.CheckConstraint(
            "quantity_value > 0 AND quantity_canonical >= 0",
            name=op.f("ck_inventory_lot_quantity_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["user_account.id"],
            name=op.f("fk_inventory_lot_created_by_user_id"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["household_id", "storage_location_id"],
            ["storage_location.household_id", "storage_location.id"],
            name=op.f("fk_inventory_lot_household_id_storage_location_id"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["household_id"],
            ["household.id"],
            name=op.f("fk_inventory_lot_household_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
            name=op.f("fk_inventory_lot_product_id"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["quantity_unit_code", "quantity_dimension"],
            ["unit.code", "unit.dimension"],
            name=op.f("fk_inventory_lot_quantity_unit_code_quantity_dimension"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_receipt_line_id"],
            ["receipt_line.id"],
            name=op.f("fk_inventory_lot_source_receipt_line_id"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inventory_lot")),
        sa.UniqueConstraint("household_id", "id", name="uq_inventory_lot_household_id"),
    )
    op.create_index(
        "ix_inventory_lot_expiry_active",
        "inventory_lot",
        ["household_id", "best_before"],
        unique=False,
        postgresql_where=sa.text("depleted_at IS NULL AND best_before IS NOT NULL"),
    )
    op.create_index(
        "ix_inventory_lot_location_active",
        "inventory_lot",
        ["household_id", "storage_location_id"],
        unique=False,
        postgresql_where=sa.text("depleted_at IS NULL"),
    )
    op.create_index(
        "ix_inventory_lot_product_active",
        "inventory_lot",
        ["household_id", "product_id"],
        unique=False,
        postgresql_where=sa.text("depleted_at IS NULL"),
    )
    op.create_index(
        "ix_inventory_lot_source_receipt_line",
        "inventory_lot",
        ["source_receipt_line_id"],
        unique=False,
    )
    op.create_index(
        "uq_inventory_lot_merge_key",
        "inventory_lot",
        ["household_id", "product_id", "storage_location_id", "best_before", "quantity_dimension"],
        unique=True,
        postgresql_where=sa.text("depleted_at IS NULL"),
        postgresql_nulls_not_distinct=True,
    )
    op.create_table(
        "stock_movement",
        sa.Column("inventory_lot_id", sa.Uuid(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "intake",
                "consumption",
                "waste",
                "adjustment",
                "transfer",
                name="stock_movement_kind",
            ),
            nullable=False,
        ),
        sa.Column("delta_canonical", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column(
            "quantity_dimension",
            sa.Enum("mass", "volume", "count", name="quantity_dimension"),
            nullable=False,
        ),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("actor_user_id", sa.Uuid(), nullable=True),
        sa.Column("recipe_suggestion_id", sa.Uuid(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("household_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("delta_canonical <> 0", name=op.f("ck_stock_movement_delta_nonzero")),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["user_account.id"],
            name=op.f("fk_stock_movement_actor_user_id"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["household_id", "inventory_lot_id"],
            ["inventory_lot.household_id", "inventory_lot.id"],
            name=op.f("fk_stock_movement_household_id_inventory_lot_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["household_id"],
            ["household.id"],
            name=op.f("fk_stock_movement_household_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["recipe_suggestion_id"],
            ["recipe_suggestion.id"],
            name=op.f("fk_stock_movement_recipe_suggestion_id"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_movement")),
    )
    op.create_index(
        "ix_stock_movement_household_occurred",
        "stock_movement",
        ["household_id", sa.literal_column("occurred_at DESC")],
        unique=False,
    )
    op.create_index(
        "ix_stock_movement_lot",
        "stock_movement",
        ["inventory_lot_id", sa.literal_column("occurred_at DESC")],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_stock_movement_lot", table_name="stock_movement")
    op.drop_index("ix_stock_movement_household_occurred", table_name="stock_movement")
    op.drop_table("stock_movement")
    op.drop_index(
        "uq_inventory_lot_merge_key",
        table_name="inventory_lot",
        postgresql_where=sa.text("depleted_at IS NULL"),
        postgresql_nulls_not_distinct=True,
    )
    op.drop_index("ix_inventory_lot_source_receipt_line", table_name="inventory_lot")
    op.drop_index(
        "ix_inventory_lot_product_active",
        table_name="inventory_lot",
        postgresql_where=sa.text("depleted_at IS NULL"),
    )
    op.drop_index(
        "ix_inventory_lot_location_active",
        table_name="inventory_lot",
        postgresql_where=sa.text("depleted_at IS NULL"),
    )
    op.drop_index(
        "ix_inventory_lot_expiry_active",
        table_name="inventory_lot",
        postgresql_where=sa.text("depleted_at IS NULL AND best_before IS NOT NULL"),
    )
    op.drop_table("inventory_lot")
    op.drop_index(
        "ix_shopping_list_item_product",
        table_name="shopping_list_item",
        postgresql_where=sa.text("product_id IS NOT NULL"),
    )
    op.drop_index(
        "ix_shopping_list_item_pending",
        table_name="shopping_list_item",
        postgresql_where=sa.text("checked_at IS NULL"),
    )
    op.drop_table("shopping_list_item")
    op.drop_index(
        "ix_recipe_ingredient_missing",
        table_name="recipe_suggestion_ingredient",
        postgresql_where=sa.text("availability IN ('missing', 'partial')"),
    )
    op.drop_table("recipe_suggestion_ingredient")
    op.drop_index(
        "ix_receipt_line_pending",
        table_name="receipt_line",
        postgresql_where=sa.text("match_status IN ('pending', 'suggested')"),
    )
    op.drop_table("receipt_line")
    op.drop_index(
        "ix_recipe_suggestion_operator_cost",
        table_name="recipe_suggestion",
        postgresql_where=sa.text("provider_mode = 'instance_owner'"),
    )
    op.drop_index("ix_recipe_suggestion_household_created", table_name="recipe_suggestion")
    op.drop_table("recipe_suggestion")
    op.drop_index(
        "ix_receipt_pending",
        table_name="receipt",
        postgresql_where=sa.text("status IN ('uploaded', 'parsing')"),
    )
    op.drop_index(
        "ix_receipt_operator_cost",
        table_name="receipt",
        postgresql_where=sa.text("provider_mode = 'instance_owner'"),
    )
    op.drop_index("ix_receipt_household_purchased", table_name="receipt")
    op.drop_table("receipt")
    op.drop_table("llm_purpose_binding")
    op.drop_index(
        "uq_storage_location_name",
        table_name="storage_location",
        postgresql_where=sa.text("archived_at IS NULL"),
    )
    op.drop_table("storage_location")
    op.drop_index(
        "uq_shopping_list_default",
        table_name="shopping_list",
        postgresql_where=sa.text("is_default AND archived_at IS NULL"),
    )
    op.drop_table("shopping_list")
    op.drop_index(
        "uq_product_household_gtin",
        table_name="product",
        postgresql_where=sa.text("household_id IS NOT NULL AND gtin IS NOT NULL"),
    )
    op.drop_index(
        "uq_product_gtin_global",
        table_name="product",
        postgresql_where=sa.text("household_id IS NULL AND gtin IS NOT NULL"),
    )
    op.drop_index(
        "ix_product_name_trgm",
        table_name="product",
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
    )
    op.drop_index(
        "ix_product_household_id",
        table_name="product",
        postgresql_where=sa.text("household_id IS NOT NULL"),
    )
    op.drop_table("product")
    op.drop_index(
        "uq_llm_provider_config_label",
        table_name="llm_provider_config",
        postgresql_where=sa.text("archived_at IS NULL"),
    )
    op.drop_index(
        "ix_llm_provider_config_invalid",
        table_name="llm_provider_config",
        postgresql_where=sa.text("status = 'invalid_credentials'"),
    )
    op.drop_index(
        "ix_llm_provider_config_household_active",
        table_name="llm_provider_config",
        postgresql_where=sa.text("archived_at IS NULL"),
    )
    op.drop_table("llm_provider_config")
    op.drop_index("ix_household_member_user_id", table_name="household_member")
    op.drop_table("household_member")
    op.drop_index("uq_user_account_email_lower", table_name="user_account")
    op.drop_table("user_account")
    op.drop_index(
        "uq_unit_canonical_per_dimension",
        table_name="unit",
        postgresql_where=sa.text("is_canonical"),
    )
    op.drop_table("unit")
    op.drop_table("llm_provider")
    op.drop_index(
        "uq_household_instance_owner",
        table_name="household",
        postgresql_where=sa.text("is_instance_owner"),
    )
    op.drop_table("household")
    # ### end Alembic commands ###

    # Native enums outlive their tables; a re-upgrade would then fail on
    # "type already exists". CASCADE is deliberately not used: at this point
    # nothing depends on them, and a dependency that does is a bug worth seeing.
    for enum_name in _ENUM_TYPES:
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")

    # Left installed on purpose: another schema in the same database may be
    # using it, and dropping a shared extension is not this migration's call.
